### ISSUE TITLE
InvalidResponseException('The response does not contain a aggregate link');

### ISSUE THREAD

**Issue by fbownz** [Shivella/laravel-bitly#1]
Good work on the package.

But I only get valid for some links but I can't get the same for all my link atempts. 
I get the exception "The response does not contain a aggregate link"

What might be causing this exception?

Thanks for your response

**Comment by Shivella** [comment]
Does that link returns a valid 200 statuscode response?
Is it a local host? Something which is not live?

If Bitly is not able to check the host it will not resolve a bitly url, which resolves into an exception.

**Comment by trevorgehman** [comment]
@Shivella I believe you are using the wrong API method. You are using `/v3/link/lookup` when you should be using `/v3/link/shorten`, which is why this error shows up for all NEW links that haven't already been shortened before.

**Comment by wahabah** [comment]
i am facing the same issue
