### ISSUE TITLE
Simplify project directory structure

### ISSUE THREAD

**Issue by klimov-paul** [Shivella/laravel-bitly#26]
Project directory structure is overcomplicated without purpose.

The 'src' directory contains redundant folders "Shivella" / "Bitly" before getting to the actual source files.
The same happens in "Tests" directory.

Instead of usage "psr-0" in composer and redundant folders it is better to switch to "psr-4" removing extra folders in the path:

```json
{
    "autoload": {
        "psr-4": {
            "Shivella\Bitly\\": "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Shivella\Bitly\\Test\\": "Tests"
        }
    },
}
```

Note: such changeset should be applied **after** other PRs are processed.

**Comment by Shivella** [comment]
Ive created a PR for this: [PR #27](https://github.com/Shivella/laravel-bitly/pull/27)
