### ISSUE TITLE
Analytics or Clicks

### ISSUE THREAD

**Issue by VimKanzoGH** [Shivella/laravel-bitly#34]
Hello Shivella,

I want to commend you for such a great package. It works great! I wanted to find out if there is a way to track clicks or get the analytics from the bitly API?

Also, one thing I noticed was that when a URL has already been processed (shortened) and for some reason, you fire the shortened event again on the same URL, it returns the below:

message: "Client error: `POST https://api-ssl.bitly.com/v4/shorten` resulted in a `400 Bad Request` response:↵{"message":"ALREADY_A_BITLY_LINK","resource":"bitlinks","description":"The value provided is invalid.","errors":[{"field (truncated...)↵"

Thank you and hoping to hear from you soon.

**Comment by Shivella** [comment]
Hey!

Bitly does support stats for clicks. Maybe we should implement retrieving those stats in this package.

Ill dive into that 400 bad request message later!

Thanks for your feedback!

**Comment by VimKanzoGH** [comment]
Hey man,

Thanks for the response.  I will be looking forward to any updates on this. If I could be of assistance, let me know how.

Regards,
Al

**Comment by VimKanzoGH** [comment]
Hello @Shivella any updates on this yet? Thanks in advance.
