### ISSUE TITLE
Update to work with Laravel 8.x

### ISSUE THREAD

**Issue by falsovsky** [Shivella/laravel-bitly#36]
Hi,

The latest Laravel version wants guzzle ^7.0.1:

https://github.com/laravel/laravel/blob/c6c41f11b8ea3065f035fbb6a6f570b7bfba0037/composer.json#L14

But the current version of the library has:

https://github.com/Shivella/laravel-bitly/blob/69b80608e7c489acf6812078f22fb7372a72b11f/composer.json#L31

So when trying to run a **composer update** we get:

```
    - Installation request for laravel/framework ^8.0 -> satisfiable by laravel/framework[8.x-dev, v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.0.4, v8.1.0, v8.2.0].
    - Installation request for shivella/laravel-bitly ^1.0 -> satisfiable by shivella/laravel-bitly[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.0.x-dev, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.1.x-dev, 6.5.x-dev].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle ^7.0.1 -> satisfiable by guzzlehttp/guzzle[7.0.1, 7.0.x-dev, 7.1.x-dev].
```

An easy fix will probably change it to "^7.0.1".

**Comment by Shivella** [comment]
I've updated the composer.json, can you try again and verify if it works?

**Comment by falsovsky** [comment]
Hi @Shivella. I can confirm it is fixed!

Already updated and it is working.

Thank you.
