### ISSUE TITLE
Does it work with lumen?

### ISSUE THREAD

**Issue by MarkAdell** [Shivella/laravel-bitly#39]

**Comment by j-xhesi** [comment]
1. Yes, it does support Lumen
2. vendor:publish command might not work. Copy ./vendor/shivella/laravel-bitly/src/BitlyServiceProvider.php  To ./app/Providers/ . Change the app/Providers/BitlyServiceProvider.php namespace to App\Providers
3. In bootstrap/app.php add `$app->register(App\Providers\BitlyServiceProvider::class);`
4. Access like `\App::make('bitly');` or register a facade and use like Bitly::getUrl
