### ISSUE TITLE
Call to a member function getStatusCode() on null

### ISSUE THREAD

**Issue by foutesting** [Shivella/laravel-bitly#40]
Hi,

I performed all the necessary steps with a laravel 8 environment. I get this message when I run $bitlyUrl = app('bitly')->getUrl($curr_url);

Call to a member function getStatusCode() on null

When I try with the second solution : use Bitly;
$url = Bitly::getUrl('https://www.google.com/'); // http://bit.ly/nHcn3

I have an error in the editor :
Non static method 'getUrl' should not be called statically

any idea?
Thanks

**Comment by Shivella** [comment]
Are you sure the package is installed correctly? Which guzzle version are you using? Seems the client does not return a response.
Unfortunately there is not that much I can fix for that in this package,

**Comment by foutesting** [comment]
Guzzle version  : "guzzlehttp/guzzle": "^7.0.1"

The debug gives me this break

BitlyClient.php:64 :

            _if ($e->getResponse()->getStatusCode() === Response::HTTP_FORBIDDEN) {
                throw new AccessDeniedException('Invalid access token.', $e->getCode(), $e);
            }_

1- the token is correctly configured in the config file
2- I test in localhost. Is this a problem?

Thank

**Comment by Shivella** [comment]
Ah ic, the Response is null in the Exception. However, your guzzle version should be compatible and it should work in localhost. Can you get some more details of that exception? What does `$e->getMessage()` returns?
