### ISSUE TITLE
cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by gabohm** [Shivella/laravel-bitly#5]
Hello, I have this error: 
InvalidResponseException in BitlyClient.php line 79: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) 

Does anyone know why this error occurs?
Thanks.

**Comment by Shivella** [comment]
It has something to do with SSL. Perhaps the SSL certificate of Bitly has been expired or not installed correctly. I cannot do anything about this issue in the package itself.

Is the error still occurring? Which OS are you using? Are you using vagrant? Or a firewall?

**Comment by gabohm** [comment]
Hi @Shivella thanks for your answer, I put 'verify'=> false in the guzzlehttp library. But I do not know if it is the best solution.
